### ISSUE TITLE
Exercise does not update solution

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/database-layer#402]
# What is wrong?
After getting a [solution ](https://de.serlo.org/entity/repository/compare/265954/265955) reviewed and checked out, the corresponding exercise continues to be an old one.

```graphql
query investigateSolutionBug {
  solution: uuid(id:265954)  {
    __typename
    ... on Solution {
      currentRevision {
        id
      }
      exercise {
        id
        currentRevision {
          id
        }
      }
      revisions {
        nodes {
          id
        }
      }
    }
  }
  currentSolutionRevision: uuid(id:265955)  {
    ... on SolutionRevision {
      content
      repository {
        id
      }
    }
  }
  exercise: uuid(id:90208) {
    ... on Exercise {
      currentRevision {
        id
      }
      solution {
        id
        currentRevision {
          id
          content
        }
      }
    }
  }
  currentExerciseRevision: uuid(id:265953) {
    __typename
  }
}
```

```json
{
  "data": {
    "solution": {
      "__typename": "Solution",
      "currentRevision": {
        "id": 265955
      },
      "exercise": {
        "id": 90208,
        "currentRevision": {
          "id": 265953
        }
      },
      "revisions": {
        "nodes": [
          {
            "id": 265955
          }
        ]
      }
    },
    "currentSolutionRevision": {
      "content": "{\"plugin\":\"solution\",\"state\":{\"prerequisite\":{\"id\":\"1337\",\"title\":\"Vierecke\"},\"strategy\":{\"plugin\":\"text\",\"state\":[{\"type\":\"p\",\"children\":[{\"text\":\"\"}]}]},\"steps\":{\"plugin\":\"rows\",\"state\":[{\"plugin\":\"text\",\"state\":[{\"type\":\"p\",\"children\":[{\"text\":\"Raute, Quadrat\"}]}]}]}}}",
      "repository": {
        "id": 265954
      }
    },
    "exercise": {
      "currentRevision": {
        "id": 265953
      },
      "solution": {
        "id": 154856,
        "currentRevision": {
          "id": 158963,
          "content": "{\"plugin\":\"solution\",\"state\":{\"prerequisite\":{\"id\":\"1705\",\"title\":\"Vierecke\"},\"strategy\":{\"plugin\":\"text\",\"state\":[{\"type\":\"p\",\"children\":[{}]}]},\"steps\":{\"plugin\":\"rows\",\"state\":[{\"plugin\":\"text\",\"state\":[{\"type\":\"p\",\"children\":[{\"text\":\"Füge hier gerne eine Lösung hinzu!\"}]}]}]}}}"
        }
      }
    },
    "currentExerciseRevision": {
      "__typename": "ExerciseRevision"
    }
  }
}
```
Notice that the exercise.solution.currentRevision.id is not the same as solution.currentRevision

# Steps to reproduce
Unfortunately it is not reproducible so far. But anyway the problem remains: how to make this exercise to get its correct solution

# Worths investigating
At the same time the exercise was edited, maybe it is hanging on the old exercise revision.

_Reported by @AndreasHuber_

**Comment by AndreasHuber** [comment]
For documentation: 
The fix made in this ticket so far makes sure that from now on no new solution is created if there is already a solution.  

When the user creates a new solution, there is a small chance that they get a "solution already exists" error if someone already made a solution but it is waiting for review and therefore not yet displayed under the exercise. The frontend may present this error case to the user in an understandable way or create a new revision instead of a new solution. 

To fix the existing cases of several solutions per exercise in the database, there is https://github.com/serlo/db-migrations/issues/7. 

In general, saving solutions and exercises separately has a number of drawbacks without a known advantage compared to saving the solution as part of the exercise. It is a plan already made before to change this at some point, though I cannot find an issue for it at the moment.
